services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userver_delivery_api
    ports:
      - "8080:8080"
    environment:
      - USERVER_LOG_LEVEL=INFO
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=delivery_db
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=password_123
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - app_network

  postgres:
    image: postgres:16-alpine
    container_name: postgres_delivery
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=delivery_db
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=password_123
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api_user -d delivery_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - app_network

  mongodb:
    image: mongo:7
    container_name: mongodb_delivery
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - ./validation.js:/docker-entrypoint-initdb.d/validation.js
      - ./queries.js:/./queries.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local
  mongo_data:

networks:
  app_network:
    driver: bridge